name: 'James Neate'
description: 'Use this GitHub Action to push Collection(s) from GitHub into a specific Postman Workspace'
author: 'jneate'
inputs:
  postmanApiKey:
    required: true
    description: 'The API Key used for the Postman Workspace'
  postmanWorkspaceId:
    required: false
    description: 'The ID for the Postman Workspace'
runs:
  using: 'node12'
  main: 'dist/index.js'
